### ISSUE TITLE
Rhino Exporter writes to previously set location, not current location

### ISSUE THREAD

**Issue by bhowes-tt** [lelandjobson/Unify#11]
**@lelandjobson @ksobon --- Let me start by saying THANK YOU in all caps for this work!!!  Congratulations - It's awesome.** :boat: :octopus: :lemon: :beer: 

I've been messing around a bit since Leland's workshop at Pratt.  I found this issue (which is minor) and another one ... which was a bit more painful (I'll create another issue for that one).

When you run UnifyExport, the form comes up with the last location you exported to:
![image](https://cloud.githubusercontent.com/assets/3171551/19734675/7781567a-9b76-11e6-8df3-f88589420325.png)

If I then change the location and press export, it writes to the previous location, not the current one in the form:
![image](https://cloud.githubusercontent.com/assets/3171551/19734753/b82ec676-9b76-11e6-840f-62dcb3dec95c.png)
![image](https://cloud.githubusercontent.com/assets/3171551/19734782/db8d7086-9b76-11e6-8de8-1876e0813b4e.png)

**Comment by ksobon** [comment]
@bhowes-tt thanks mate! It's great to hear that you like it. Now, we just got to make it work. :-) 

I think what might happen is that if you paste the location in using for example CTR + C and CTR + V the event doesn't fire on that location text box and doesn't update the location. Is that what happened? I think if I remember correctly I only have an event hooked up to the "..." button, and if I was to just copy/paste it won't work. I might be remembering wrong, but also I will check this out.

**Comment by bhowes-tt** [comment]
@ksobon - excellent!

It could be a copy/paste thing, or I might've just changed the path by hand (I was doing a lot of 001, 002, 003 sort of stuff).

**Comment by ksobon** [comment]
yeah, i had that location be set only when you fire the open file dialog event so when clicking on the button. I added a small check at the end to cover a case when user just pasted it in. Should be good now.
