### ISSUE TITLE
OBJ export settings

### ISSUE THREAD

**Issue by bhowes-tt** [lelandjobson/Unify#12]
@lelandjobson - I figured out why I was getting an all white model with no mesh colliders, as we saw together during your Digital Futures workshop at Pratt.  I spent most of yesterday debugging the Editor Scripts on the Unity side to see if I could sniff it out (which was actually super fun... I was chasing the wrong lead but I got a good feel for the project along the way), but the issue is actually on the rhino side.

In order for Objects to be grouped by layer in the exported OBJ file (which is critical for Unify to assign materials and colliders correctly on the Unity side), I had to set this manually in Rhino's export [obj] dialog:
![image](https://cloud.githubusercontent.com/assets/3171551/19735043/eb7c4b24-9b77-11e6-9613-6575414f1cf8.png)

I tried messing with the Rhino plugin's code in [/Unify/Utilities](https://github.com/lelandjobson/Unify/blob/master/Unify/Utilities.cs#L62-L101), which looks like it's supposed to handle this sort of stuff, but it never made a difference - the only way to get objects grouped by layer was to set this myself outside of Unify, and then run UnifyExport again.

**Comment by ksobon** [comment]
Hi @bhowes-tt , this is exactly what was supposed to handle that setting. I guess i never realized that it wasn't getting set properly since I first must have set that in my Rhino manually about 100 times when I was working with Unity. Anyways, that's a great catch, I will have a look at that bit again, and see if we can fix it.

**Comment by ksobon** [comment]
I cleaned that out and now all settings are getting set properly. The issue was the `UnknownCommand = y=y` that was getting passed into the command line. I am not sure why I put that in there. The two `_Enter _Enter` do the job just fine. Anyways that should be fixed now.
